server:
  port: 8080
  context: "/"
  mode: "release"
config:
  dir: "config"
logging:
  format: "json"
  level:
    "/": "error"
#git:
#  url: https://github.com/some-org/config.git
#  branch: publish
#  username: SOME_TOKEN
#  token: value